version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: SistemaManutencao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    container_name: wildfly_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./wildfly_logs:/opt/jboss/wildfly/standalone/log
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
